package com.cherrydev.airsend.app.settings;

public enum PreferenceKey {
    LAST_USED_PSK,
    DEVICE_NAME,
    SEND_CLIPBOARD,
    CONNECT_TO_KNOWN_DEVICES,
    START_ON_BOOT,
    SHOW_NOTIFICATIONS,
    SHOW_MESSAGE_NOTIFICATIONS,
    SHOW_NOTIFICATIONS_MESSAGE,
    OPEN_LINKS_ON_CLICK,
    DEBUG_OPTIONS,
    LAST_USED_PORT,
}
